apiVersion: v1
kind: ConfigMap
metadata:
  name: hms-config
  namespace: hms
data:
  KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  JWT_EXPIRATION_MS: "3600000"
  AUTH_SERVICE_URL: "http://auth-service:8080"
  PATIENT_SERVICE_URL: "http://patient-service:8081"
  DOCTOR_SERVICE_URL: "http://doctor-service:8082"
  DEPARTMENT_SERVICE_URL: "http://department-service:8083"
  APPOINTMENT_SERVICE_URL: "http://appointment-service:8084"
